name: Build and Deploy PDF
on:
  push:
    branches: 
      - main

permissions: 
    contents: write
    pages: write

jobs:
  quarto-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      # From https://github.com/actions/setup-python
      - name: Setup Python
        uses: actions/setup-python@v3

      # From https://github.com/r-lib/actions/tree/v2-branch/setup-r
      - name: Setup R
        uses: r-lib/actions/setup-r@v2
        with:
          packages:
            any::knitr
            any::rmarkdown
      
      - name: Setup Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        with:
          tinytex: true
          version: 1.4.551

      - name: Render Quarto Project
        uses: quarto-dev/quarto-actions/render@v2
        with:
          to: pdf # If set, it will be equivalent to `quarto render --to html`
          path: issues-01.qmd # By default, the current working dir is used i.e `quarto render .`

      - name: Upload PDF as artifact
        uses: actions/upload-artifact@v2
        with:
          name: template.pdf
          path: main.pdf
